POST http://localhost:5000/user/register
Content-Type: application/json

{
    "email":"test2@gmail.com",
    "username": "test2",
    "password": "123456",
    "gender":"male",
    "phone": "0123456",
    "fullname": "huy1"
}

###
#PATCH là một cập nhập một phần
#PUT là cập nhập tât cả

# POST http://localhost:5000/user/login
# Content-Type: application/json

# {
#     "email": "test@gmail.com",
#     "password": "123456"
# }

get http://localhost:5000/user/search?fullname=huy1

