export const ADD_NEW_DATE = "ADD_NEW_DATE";
export const ADD_NEW_LOCATION = "ADD_NEW_LOCATION";
export const DELETE_DATE = "DELETE_DATE";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const RESET_TOUR = "RESET_TOUR";